import type { BusinessType, Vocabulary } from "./types";

const base = {
  priceLabel: "Price",
  categoryLabel: "Category",
  statusLabels: {
    available: "Available",
    pending: "Pending",
    featured_deal: "Featured",
    sold: "Sold",
    coming_soon: "Coming soon",
  },
};

export const VOCAB: Record<BusinessType, Vocabulary> = {
  real_estate: {
    ...base,
    label: "Real estate",
    itemSingular: "Listing",
    itemPlural: "Listings",
    specHints: ["Beds", "Baths", "Sq ft", "Lot size", "Year built", "HOA"],
    sample: { title: "412 Wisteria Lane", subtitle: "4 bed · 3 bath · 2,840 sq ft", price: "$895,000" },
    statusLabels: { ...base.statusLabels, pending: "Under offer", sold: "Sold" },
  },
  automotive: {
    ...base,
    label: "Automotive",
    itemSingular: "Vehicle",
    itemPlural: "Inventory",
    specHints: ["Mileage", "Transmission", "Drivetrain", "Engine", "Exterior", "VIN"],
    sample: { title: "2023 Toyota Tacoma TRD", subtitle: "12,400 mi · 4WD · One owner", price: "$41,200" },
    statusLabels: { ...base.statusLabels, pending: "On hold" },
  },
  restaurant: {
    ...base,
    label: "Restaurant & food",
    itemSingular: "Menu item",
    itemPlural: "Menu",
    priceLabel: "Price",
    categoryLabel: "Course",
    specHints: ["Serves", "Spice", "Allergens", "Calories"],
    sample: { title: "Charred Miso Eggplant", subtitle: "Sesame, scallion, ginger crisp", price: "$18" },
    statusLabels: { ...base.statusLabels, sold: "Sold out", available: "On the menu" },
  },
  beauty: {
    ...base,
    label: "Beauty & wellness",
    itemSingular: "Service",
    itemPlural: "Services",
    priceLabel: "From",
    categoryLabel: "Service type",
    specHints: ["Duration", "Stylist", "Aftercare", "Patch test"],
    sample: { title: "Balayage + Gloss", subtitle: "Full head, includes toner", price: "$240" },
    statusLabels: { ...base.statusLabels, sold: "Fully booked" },
  },
  fitness: {
    ...base,
    label: "Fitness & coaching",
    itemSingular: "Program",
    itemPlural: "Programs",
    priceLabel: "From",
    categoryLabel: "Format",
    specHints: ["Length", "Sessions/week", "Level", "Location"],
    sample: { title: "12-Week Strength Rebuild", subtitle: "3x per week · hybrid coaching", price: "$480" },
    statusLabels: { ...base.statusLabels, sold: "Cohort full" },
  },
  professional: {
    ...base,
    label: "Professional services",
    itemSingular: "Service",
    itemPlural: "Services",
    priceLabel: "From",
    categoryLabel: "Practice area",
    specHints: ["Turnaround", "Format", "Includes", "Best for"],
    sample: { title: "Fractional CFO Retainer", subtitle: "Monthly close, board pack, forecast", price: "$3,500" },
    statusLabels: { ...base.statusLabels, sold: "Waitlist" },
  },
  retail: {
    ...base,
    label: "Retail & ecommerce",
    itemSingular: "Product",
    itemPlural: "Products",
    specHints: ["Material", "Size", "Colour", "Ships in"],
    sample: { title: "Field Tote — Waxed Canvas", subtitle: "Charcoal · 18L · leather trim", price: "$168" },
    statusLabels: { ...base.statusLabels, sold: "Sold out", coming_soon: "Restocking" },
  },
  creative: {
    ...base,
    label: "Creative & media",
    itemSingular: "Package",
    itemPlural: "Work",
    priceLabel: "From",
    categoryLabel: "Discipline",
    specHints: ["Deliverables", "Turnaround", "Revisions", "Usage"],
    sample: { title: "Brand Film — Half Day", subtitle: "2 finished cuts + social edits", price: "$2,400" },
    statusLabels: { ...base.statusLabels, sold: "Booked" },
  },
  events: {
    ...base,
    label: "Events & venues",
    itemSingular: "Event",
    itemPlural: "Events",
    priceLabel: "Tickets from",
    categoryLabel: "Type",
    specHints: ["Date", "Doors", "Capacity", "Age"],
    sample: { title: "Rooftop Supper Club", subtitle: "Fri 14 Nov · 7:00pm · 40 seats", price: "$95" },
    statusLabels: { ...base.statusLabels, sold: "Sold out", coming_soon: "On sale soon" },
  },
  trades: {
    ...base,
    label: "Trades & home services",
    itemSingular: "Service",
    itemPlural: "Services",
    priceLabel: "From",
    categoryLabel: "Service type",
    specHints: ["Callout", "Warranty", "Lead time", "Coverage"],
    sample: { title: "Emergency Leak Repair", subtitle: "24/7 callout · 90-day warranty", price: "$180" },
    statusLabels: { ...base.statusLabels, sold: "Unavailable" },
  },
  other: {
    ...base,
    label: "Something else",
    itemSingular: "Item",
    itemPlural: "Showcase",
    specHints: ["Detail", "Detail", "Detail"],
    sample: { title: "Featured offer", subtitle: "A short supporting line", price: "$—" },
  },
};

export const BUSINESS_TYPES = Object.keys(VOCAB) as BusinessType[];

export function vocab(type: BusinessType | string | undefined): Vocabulary {
  return VOCAB[(type as BusinessType) ?? "other"] ?? VOCAB.other;
}
